# Generated by Django 4.1.2 on 2022-11-20 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="profile_photo",
            new_name="avatar",
        ),
    ]
