# Generated by Django 4.1.2 on 2022-11-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_room_amenites_alter_amenity_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="neme",
            field=models.CharField(default="", max_length=180),
        ),
    ]
