# Generated by Django 4.1.2 on 2022-11-27 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0003_room_neme"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="neme",
            new_name="name",
        ),
    ]
