# Generated by Django 4.1.2 on 2022-11-27 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0004_rename_neme_room_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amenity",
            options={"verbose_name_plural": "Amenities"},
        ),
        migrations.RenameField(
            model_name="room",
            old_name="amenites",
            new_name="amenities",
        ),
    ]
